export const products = [
    {
      id: 1,
      name: "Men 3 Quater Sleeve Senator Wear",
      price: "NGN23,000.00",
      discount: "-20% off",
      image: "/images/Rectangle1.jpg",
      category: "Men",
    },
    {
      id: 2,
      name: "Ladies Unique Cooperate Gown",
      price: "NGN11,000.00",
      discount: "-26% off",
      image: "/images/Rectangle2.jpg",
      category: "Women",
    },
    {
      id: 3,
      name: "Gorgeous and Stylish Ladies Corporate Skirt",
      price: "NGN65,000.00",
      discount: "-23% off",
      image: "/images/Rectangle3.jpg",
      category: "Women",
    },
    {
      id: 4,
      name: "Gorgeous And Exquisite Ladies Gown And Jacket",
      price: "NGN11,000.00",
      discount: "-16% off",
      image: "/images/Rectangle4.jpg",
      category: "Women",
    },
    {
      id: 5,
      name: "Classic Quality Men's Agbada",
      price: "NGN65,000.00",
      discount: "-13% off",
      image: "/images/Rectangle5.jpg",
      category: "Men",
    },
    {
      id: 6,
      name: "Classic Men’s Senator - Peach",
      price: "NGN34,000.00",
      discount: "-13% off",
      image: "/images/Rectangle6.jpg",
      category: "Men",
    },
  ];