export const products = [
    {
      id: 1,
      name: "Inalsa Air Fryer Fry-Light-1400W",
      price: "NGN4,627.00",
      discount: "-40% off",
      image: "/images/Rectangle1.png",
      category: "Kitchen",
    },
    {
      id: 2,
      name: "Oneplus Bullets Z2 Bluetooth Wireless",
      price: "NGN1,699.00",
      discount: "-26% off",
      image: "/images/Rectangle2.png",
      category: "Audio",
    },
    {
      id: 3,
      name: "New Fastrack Reflex Play! AMOLED Display",
      price: "NGN5,699.00",
      discount: "-23% off",
      image: "/images/Rectangle3.png",
      category: "Wearables",
    },
    {
      id: 4,
      name: "Apple iPhone 13 (128GB) - Green",
      price: "NGN56,900.00",
      discount: "-16% off",
      image: "/images/Rectangle4.png",
      category: "Mobile",
    },
    {
      id: 5,
      name: "Samsung Galaxy Tab S8+ - Wifi Only, Graphite",
      price: "NGN74,998.00",
      discount: "-13% off",
      image: "/images/Rectangle5.png",
      category: "Tablets",
    },
    {
      id: 6,
      name: "Kodak Mini Shot 3 Retro - Yellow, Bluetooth",
      price: "NGN74,998.00",
      discount: "-13% off",
      image: "/images/Rectangle6.png",
      category: "Camera",
    },
  ];